name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download Dependencies
        run: ./gradlew build --stacktrace

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: List APK files
        run: ls app/build/outputs/apk/debug

      - name: Capture APK file name
        id: capture-apk-name
        run: echo "APK_NAME=$(basename $(ls app/build/outputs/apk/debug/myNavigationDemoApp-*.apk))" >> $GITHUB_ENV

      - name: Print APK Name
        run: echo "APK Name is ${{ env.APK_NAME }}"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/debug/${{ env.APK_NAME }}

      - name: Upload to TestFairy
        env:
          TF_ACCESS_KEY: ${{ secrets.TF_ACCESS_KEY }}
        run: |
              curl https://upload.testfairy.com/api/upload \
                -F api_key=$TF_ACCESS_KEY \
                -F file=@app/build/outputs/apk/debug/${{ env.APK_NAME }} \
                -F groups="Android_S22" \
                -F notify="on" 
